language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2

sudo: false

env:
  global:
    - DEFAULT=1

matrix:
  fast_finish: true
  include:
    - php: 7.2

install:
  - composer self-update
  - composer install --dev

before_script:
  - cp phpunit.xml.dist phpunit.xml

script:
  - sh -c "if [ '$DEFAULT' = '1' ]; then vendor/bin/phpunit --stderr; fi"

notifications:
  email: false
